\input texinfo   @c -*-mode:texinfo;fill-column:79;-*-
@comment %**start of header
@setfilename autoconf-archive.info
@settitle Autoconf Archive
@ifclear texi2html
@paragraphindent none
@end ifclear
@comment %**end of header

@include version.texi

@copying
This manual is for Autoconf Archive version @value{VERSION}, a collection of
freely re-usable Autoconf macros.

Compilation Copyright @copyright{} 2010 Autoconf Archive Maintainers
@email{autoconf-archive-maintainers@@nongnu.org}

This compilation is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This compilation is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
@end copying

@dircategory Software development
@direntry
* Autoconf Archive: (autoconf-archive).     A collection of re-usable Autoconf macros.
@end direntry

@titlepage
@title Autoconf Archive
@subtitle Version @value{VERSION}
@author @email{autoconf-archive-maintainers@@nongnu.org}
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c @contents

@ifnottex
@node Top
@top Autoconf Archive

@insertcopying
@end ifnottex

@menu
* Introduction::
* Using the Autoconf Archive::
* Contributing to the Autoconf Archive::
* The Macros::
@end menu

@node Introduction
@chapter Introduction
@include introduction.texi

@node Using the Autoconf Archive
@chapter Using the Autoconf Archive
@include using.texi

@node Contributing to the Autoconf Archive
@chapter Contributing to the Autoconf Archive
@include contribute.texi

@node The Macros
@chapter The Macros
@include all-macros.texi

@bye
